language: node_js
node_js:
 - "5"

before_install: npm i -g npm && rvm install 2
install: npm i && gem install jekyll html-proofer

before_script: npm run gulp build
script: jekyll build && htmlproofer ./_site
sudo: required
